# Generated by Django 5.2.12 on 2026-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course_enrollment_lesson_progress'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='idx_course_created_at'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'created_at'], name='idx_instructor_created'),
        ),
    ]
